name: Build on PR
"on": pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing Dependencies
        run: yarn
      - name: Building App
        run: yarn run build
  cypress_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Increase Watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Installing Dependencies
        run: yarn
      - name: Starting Server
        run: yarn start & npx wait-on http://localhost:3000
      - name: Run Cypress with Percy
        run: yarn run percy
  preview_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing Dependencies
        run: yarn
      - name: Building App
        run: yarn run build
      - name: Deploy to Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PHOTOSHOP_ONLINE_3635D }}"
          expires: 4d
          projectId: photoshop-online-3635d
